on:
  push:
    brances:
      - main
  pull_request:

name: tests

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v1
      - run: curl -s -LO https://29617-80669528-gh.circle-artifacts.com/0/~/artifacts/ddev_linux-amd64.v1.16.2-alpha2-6-gd22dce22.tar.gz && tar -zxf ddev_linux-amd64*tar.gz && sudo mv ddev mkcert /usr/local/bin && mkcert -install
      - run: ddev config global --instrumentation-opt-in=false --omit-containers=dba,ddev-ssh-agent
#      - run: curl -LO https://raw.githubusercontent.com/drud/ddev/master/scripts/install_ddev.sh && bash install_ddev.sh
      - run: mkdir junk && cd junk && ddev config --project-type=php && ddev start
      - run: echo "this is junk"> ~/junk/index.html
      - run: curl -s https://junk.ddev.site
      - uses: mxschmitt/action-tmate@v3
      - run: curl -s https://junk.ddev.site | grep "this is junk"

