on: [push, pull_request]
name: tests

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v1
      - run: curl -LO https://raw.githubusercontent.com/drud/ddev/master/scripts/install_ddev.sh && bash install_ddev.sh
      - run: mkdir junk && cd junk && ddev config --project-type=php && ddev start
