# This temporary test of nginx.tmpl is here to demonstrate that
# ddev (ddev-router) can now run successfully on github actions linux
on:
  push:
    branches:
      - master
  pull_request:

name: test ddev-router's nginx.tmpl generation

jobs:
  test:
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]
    steps:
      - uses: actions/checkout@v1
      - run: make
      - run: sudo cp .gotmp/bin/*/ddev /usr/local/bin
      - run: sudo curl -lL -s -o /usr/local/bin/mkcert https://github.com/drud/mkcert/releases/download/v1.4.6/mkcert-v1.4.6-$(go env GOOS)-amd64 && sudo chmod +x /usr/local/bin/mkcert
#      - run: curl -s -LO https://29617-80669528-gh.circle-artifacts.com/0/~/artifacts/ddev_linux-amd64.v1.16.2-alpha2-6-gd22dce22.tar.gz && tar -zxf ddev_linux-amd64*tar.gz && sudo mv ddev mkcert /usr/local/bin && mkcert -install
      - run: ddev config global --instrumentation-opt-in=false --omit-containers=dba,ddev-ssh-agent
#      - run: curl -LO https://raw.githubusercontent.com/drud/ddev/master/scripts/install_ddev.sh && bash install_ddev.sh
      - run: cd testsite && ddev config --project-type=php && ddev start
      - run: docker inspect --format "{{json .State.Health }}" ddev-router | jq -r .Log[-1].Output | grep "ddev-router is healthy with 2 upstreams"
#      - uses: mxschmitt/action-tmate@v3
      - run: curl -s https://testsite.ddev.site | grep "This is testsite"

